Add JAXB to dependencies to be able to compile with java 9 and older
java-deobfuscator/deobfuscator pull request #602
Opened 2020-07-26 12:54 UTC by GitAntoinee

I added JAXB to dependencies to be able to compile with java 9 and older (I tried with `openjdk 14.0.1 2020-04-14`).

2020-07-26 20:03 UTC, Janmm14 commented
you probably meant to be able to compile with java 9 and **newer**

2020-07-26 20:09 UTC, GitAntoinee commented
You're right, I do not speak English very well unfortunately

2021-05-29 12:14 UTC, Janmm14 requested changes

2021-05-29 12:14 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java
> +    		//insnCount.get(Opcodes.ISHL) == null ||
unrelated change, should be left out

2021-05-29 12:14 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/allatori/StringEncryptionTransformer.java
> +               //insnCount.get(Opcodes.ISHL).get() >= 1 &&
unrelated change, should be left out

2021-05-29 12:14 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/executor/defined/JVMMethodProvider.java
> +        }});
unrelated change, should be left out

2021-05-31 13:36 UTC, GitAntoinee commented
you're right janm it wasn't related to the title you finally saw it after almost 1 year xd. I've forgotten this pr

2021-08-03 17:00 UTC, ThisTestUser commented
There's too much conflicts in this PR to merge (plus there's already Github Actions).

2021-08-03 17:00 UTC, closed without merging