Add class-file support for ASM-crashing classes using CAFED00D
java-deobfuscator/deobfuscator pull request #727
Opened 2021-03-28 21:48 UTC by Col-E

Resolves #726

2021-03-28 23:26 UTC, Janmm14 requested changes

2021-03-28 23:26 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java
> +        ClassNode clazz = classpath.get(ref.replace('/', '.'));
Classes are stored in this project by their internal name, so this change is wrong.

2021-03-28 23:26 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java
> +        ClassNode clazz = classpath.get(ref.replace('/', '.'));
Same as above

2021-03-28 23:30 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java
> +        ClassWriter writer = new CustomClassWriter(ClassWriter.COMPUTE_FRAMES);
COMPUTE_FRAMES requires all libs to be added afaik. I believe thiy was not used on purpose as this is not needed for many deobfuscation steps.

2021-03-28 23:51 UTC, Col-E commented on src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java
> +        ClassNode clazz = classpath.get(ref.replace('/', '.'));
In my test case I got a clear case of `ref` containing `.` which is why I added it. I can revert it if you insist.

2021-03-29 00:28 UTC, Janmm14 commented on src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java
> +        ClassNode clazz = classpath.get(ref.replace('/', '.'));
See
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L109
and
https://github.com/java-deobfuscator/deobfuscator/blob/master/src/main/java/com/javadeobfuscator/deobfuscator/Deobfuscator.java#L132

The map is filled with asm's classname which is the internal full representation.

If you got a call to that method with a dotted class name, it is either a bug of the deobfuscator or some sneaky obfuscation which tries to exploit possible weaknesses of java-deobfuscator.

2021-03-29 00:34 UTC, Col-E commented
Anyways, resolved the review comments 👍

2021-03-30 07:31 UTC, ItzSomebody approved these changes

2021-04-13 06:19 UTC, Col-E commented
I updated CAFED00D with more support. And the only diff for future support will just be versioning bumps :)

2021-04-13 09:34 UTC, Janmm14 commented
@ThisTestUser

2021-04-13 14:31 UTC, merged