Optimi ParamorphismTransformer
java-deobfuscator/deobfuscator pull request #766
Opened 2021-05-22 05:49 UTC by BackupAccou

What Changed: 
1. Removed the field OVRERIDE since it's useless
2. Moves the replace loop out side of the interface decryption loop.

2021-05-22 05:55 UTC, fee1-dead requested changes
I saw that you had issues with squashing commits, so when you make a change, you amend the commit (edit the commit) and force-push it.

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +
```suggestion
MethodInsnNode min = (MethodInsnNode) ain;
```

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +						if (!replacements.containsKey(((MethodInsnNode) ain).owner)) {
```suggestion
						if (!replacements.containsKey(min.owner)) {
```

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +										((MethodInsnNode) ain).owner, cn.name, mn.name, mn.desc));
```suggestion
										min.owner, cn.name, mn.name, mn.desc));
```

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +						Map<MethodNode, AbstractInsnNode> map = replacements.get(((MethodInsnNode) ain).owner);
```suggestion
						Map<MethodNode, AbstractInsnNode> map = replacements.get(min.owner);
```

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +						MethodNode caller = map.keySet().stream().filter(m -> m.name.equals(((MethodInsnNode) ain).name)
```suggestion
						MethodNode caller = map.keySet().stream().filter(m -> m.name.equals(min.name)
```

2021-05-22 05:55 UTC, fee1-dead commented on src/main/java/com/javadeobfuscator/deobfuscator/transformers/special/ParamorphismTransformer.java
> +								&& m.desc.equals(((MethodInsnNode) ain).desc)).findFirst().orElse(null);
```suggestion
								&& m.desc.equals(min.desc)).findFirst().orElse(null);
```

2021-05-22 07:34 UTC, BackupAccou commented
@fee1-dead Why should ClassCast being removed ? It makes no sense. Please provide reasons.

2021-05-22 08:26 UTC, Janmm14 commented
> @fee1-dead Why should ClassCast being removed ? It makes no sense. Please provide reasons.

The idea is to classcast once (see first suggested change) and safe it in a new variable. Code looks cleaner then.

2021-05-22 09:28 UTC, BackupAccou commented
@Janmm14 not necessary i think

2021-05-22 09:30 UTC, fee1-dead commented
Casting multiple times makes no sense. Do it once, and it saves space, makes the code easier to read.

2021-05-22 09:33 UTC, fee1-dead commented
Even if the code ends up having the same behavior, style issues can develop and become a habit. Please fix this. It is quick and simple.

2021-05-22 11:34 UTC, fee1-dead commented
@Maintainers, I think you are allowed to edit, so maybe you can help him squash the commits?

2021-05-22 11:51 UTC, closed without merging

2021-05-23 03:29 UTC, ItzSomebody commented
> Maintainers, I think you are allowed to edit, so maybe you can help him squash the commits?

It should be enabled by default, yes.

@BackupAccou:  Is there a reason why you closed this?